# .streamlit/secrets.toml
# This file satisfies the requirement of some hosting services (like Streamlit Cloud)
# for a secrets file to exist when using cache_data/cache_resource.
# No actual secret is needed for public FastF1 data.
streamlit_test_key = "dummy_value"